name: "Check Online Version"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * *"
env:
  FLUTTER_PROJECT_NAME: flutter-cmake # Dockerhub project
jobs:
  get_versions:
    name: Get Versions
    runs-on: ubuntu-latest
    outputs:
      current_flutter_image_version: ${{ steps.read_version.outputs.version }}
      latest_flutter_image_version: ${{ steps.latest_versions.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Release
      id: latest_versions
      run: |
        chmod +X ./manifest/scripts/dockertags.sh
        echo "::set-output name=tag::$(./manifest/scripts/dockertags.sh cirrusci/flutter | sed 's/^v//' | grep -P '^(\d{1,}\.){2}\d{1,}$' | sort)"
        
    - name: Log latest image Tag
      run: |
        echo "Latest Image Tag - ${{ steps.latest_versions.outputs.tag }}"

    - name: Read Version
      id: read_version
      run: |
        chmod +X ./manifest/scripts/githubtags.sh
        echo "::set-output name=version::$(./manifest/scripts/githubtags.sh daanh432/flutter-cmake | sed 's/^v//' | grep -P '^(\d{1,}\.){2}\d{1,}$' | sort)"
        
    - name: Log current image Tag
      run: |
        echo "Current Image Tag - ${{ steps.read_version.outputs.version }}"

  update_versions:
    name: Update version.txt
    runs-on: ubuntu-latest
    needs: get_versions
    if: needs.get_versions.outputs.latest_flutter_image_version != needs.get_versions.outputs.current_flutter_image_version
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo -e "${{ needs.get_versions.outputs.latest_flutter_image_version }}" > ./manifest/versions.txt
        echo -e "${{ needs.get_versions.outputs.current_flutter_image_version }}" > ./manifest/supported_versions.txt
        comm -23 ./manifest/versions.txt ./manifest/supported_versions.txt | sort -Vr > ./manifest/unprocessed_versions.txt
        git commit -a -m "Automatically updated versions."
        git push
  
#   request-flutter-image-build:
#     uses: ./.github/workflows/update-flutter-cmake-image.yml
